title: PonteWire
description: High-Performance Reactive Webhook Bridge built with Java 25 & Kafka
theme: jekyll-theme-cayman

# Configurazione per il monitoraggio dei visitatori (Svizzera, arriviamo!)
google_analytics: G-2267FDDYZC

show_downloads: true