server:
  port: 8081

spring:
  application:
    name: pw-worker
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/pontewire_db
    username: admin
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: pw-worker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces