apiVersion: v1
kind: Service
metadata:
  name: pw-worker
spec:
  selector:
    app: pw-worker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: {{ .Values.worker.port }}
  type: ClusterIP