spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/pontewire_db
    username: admin
    password: password
  application:
    name: pw-gateway
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    admin:
      auto-create: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
      tracing:
        endpoint: http://localhost:4318/v1/traces
server:
  port: 8080

pontewire:
  hmac:
    secret: "top secret =) "